### ISSUE TITLE
ValueError in run_statistical_tests.py

### ISSUE THREAD

**Issue by HalvarKelm** [jordanbehrendt/good_practices_ml#15]
When running `run_statistical_tests.py` we are faced with the following error:
```shell
Traceback (most recent call last):
  File "src/CLIP_Experiment/run_statistical_tests.py", line 177, in <module>
    run_analysis_of_experiments(REPO_PATH, 'Mixed_F1')
  File "src/CLIP_Experiment/run_statistical_tests.py", line 148, in run_analysis_of_experiments
    default_df[f'{dataset}'] = default_list
    ~~~~~~~~~~^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/pandas/core/frame.py", line 3950, in __setitem__
    self._set_item(key, value)
  File "lib/python3.11/site-packages/pandas/core/frame.py", line 4143, in _set_item
    value = self._sanitize_column(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/pandas/core/frame.py", line 4870, in _sanitize_column
    com.require_length_match(value, self.index)
  File "lib/python3.11/site-packages/pandas/core/common.py", line 576, in require_length_match
    raise ValueError(
ValueError: Length of values (270) does not match length of index (200)
``` 
The command used to run this was simply `run_statistical_tests.py --user default --yaml_path paths.yaml`.
Specifically, the error occurs when the `dataset` variable is set to "aerial", so we assume a problem in our aerial dataset which has worked fine with all other scripts before. The loop iteration works for both "geoguessr" and "tourist" datasets (if we swap the order) as the `default_df` contains the correct columns afterwards.

**Comment by RamiAI** [comment]
We have also created a Dockerfile that makes it possible to reproduce this error. However, it is no longer based on the main branch, as that led to other errors. We selected a commit from the beginning of the week. 

We will take a closer look at the current changes in the main branch next week.

**Download:** https://nc.uni-bremen.de/index.php/s/jQDDfJqt7i7PJSi

**Steps to reproduce:**
1. Download the folder
2. Build a Dockerimage via `podman build -t gpml -f Dockerfile . `
3. Start a docker container with `podman run --gpus=all -v <local_dataset_folder>:/app/dataset --rm -it gpml /bin/bash` and replace `<local_dataset_folder>` with the folder that contains the three datasets.
4. Execute the following scripts:
```bash
python3 CLIP_Experiment/run_datasets_and_prompts.py --user "default" --yaml_path paths.yaml
python3 CLIP_Experiment/evaluate_results_with_metrics.py --user "default" --yaml_path paths.yaml
python3 CLIP_Experiment/run_statistical_tests.py --user "default" --yaml_path paths.yaml
```

```python
Traceback (most recent call last):
  File "CLIP_Experiment/run_statistical_tests.py", line 177, in <module>
    run_analysis_of_experiments(REPO_PATH, 'Mixed_F1')
  File "CLIP_Experiment/run_statistical_tests.py", line 148, in run_analysis_of_experiments
    default_df[f'{dataset}'] = default_list
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3950, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 4143, in _set_item
    value = self._sanitize_column(value)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 4870, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/common.py", line 576, in require_length_match
    raise ValueError(
ValueError: Length of values (270) does not match length of index (200)
```

**Comment by taylorkrn** [comment]
Hi!
I have a few questions:
1. Does it only occur when you run statistical tests with aerial? Or also with other datesets?
2. Did you download the aerial data from osf or did you generate the 'aerial' data yourself using the aerial_data_collection.py script?
Thanks!

**Comment by taylorkrn** [comment]
The latest commit to main is updated so that you no longer need to give a '--user' argument. If you update this and your paths.yaml file then everything should work as before

**Comment by taylorkrn** [comment]
I think this issue should be fixed now on main. Please check and let me know!

**Comment by HalvarKelm** [comment]
The issue is related to the `aerial_data_collection.py` script. That script downloads 234.7MB of data while the data provided on OSF only has a size of 175.2MB.
After using the OSF data, the script runs without issue.
Thank you for looking into it!
